<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WPF_Modul_Test</AssemblyName>
    <RootNamespace>WPF_Modul_Test</RootNamespace>
  </PropertyGroup>

</Project>