<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DocuMan.UI.Common</RootNamespace>
    <AssemblyName>DocuMan.UI.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ADaxer.MvvmNav.Core" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain.Models\Domain.Models.csproj" />
  </ItemGroup>

</Project>
