<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QET.Styles\QET.Styles.csproj" />
    <ProjectReference Include="..\TestSuite.Common\TestSuite.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\SetupView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
