<Project>
  <PropertyGroup>
	<!-- Enable Central Package Management -->
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
	<!-- Central package versions for the solution -->
	<PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	<PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
  </ItemGroup>

</Project>
