<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <RootNamespace>CustomLayouts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomControls\M21_CustomControls_optional.csproj" />
  </ItemGroup>

</Project>
