<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\MyFont.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\M016\M016_Animations_LabLoesung\Lab16_Loesung.csproj" />
    <ProjectReference Include="..\CustomControls\M21_CustomControls_optional.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\MyFont.ttf" />
  </ItemGroup>

</Project>
